version: '3.9'

services:
# database container image
  postgres:
    image: postgres:13-alpine
  
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
   
  
    restart: always
#web container image
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - default
    restart: unless-stopped
volumes:
  data:

    

